#if !canImport(ObjectiveC)
import XCTest

extension SQLiteNIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQLiteNIOTests = [
        ("testExample", testExample),
        ("testZeroLengthBlob", testZeroLengthBlob),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SQLiteNIOTests.__allTests__SQLiteNIOTests),
    ]
}
#endif
